### PR TITLE
Updates UID:s in the test data to remove invalid values

### PR DESCRIPTION
**Pull request by BwKodex**
Changed the UID:s in the test DICOM files to remove invalid UID:s and the related warnings from pydicom when reading the data.

### CODE REVIEW

**Comment by MaxHellstrom** [comment]
I stilll get warning messages on "siemens_axiom_artis.dcm", "philips_allura_clarity_u104.dcm", and "philips_allura_clarity_u601.dcm". I am using pydicom version 3.0.1. 

Any ideas why?

**Comment by MaxHellstrom** [comment]
E.g. "Invalid value for VR UI: '1.2.826.0.1.3680043.8.971.00.37881344602234345332104216659618145'." with "philips_allura_clarity_u601.dcm"

**Comment by BwKodex** [comment]
Well... it could be because I made a double error. One in the loop replacing invalid UID values and one in the validation run. :) 

I've had another go at it now. Could you @MaxHellstrom  try and verify that the new UID don't give any warnings on your end now.

**Comment by MaxHellstrom** [comment]
Thanks. All files works now!

**Review by MaxHellstrom — APPROVED** [review]

**Pull request merged**
