### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BwKodex**
Adds a codecov-badge to the top of the readme

### CODE REVIEW

**Comment by notZaki** [comment]
Could add a CI badge too:
```
[![ci](https://github.com/rvbCMTS/PySkinDose/actions/workflows/ci.yml/badge.svg)](https://github.com/rvbCMTS/PySkinDose/actions/workflows/ci.yml)
```

**Comment by BwKodex** [comment]
Good suggestion @notZaki. Added it.

**Comment by notZaki** [comment]
How about a badge for the documentation as well?
```
[![Documentation Status](https://readthedocs.org/projects/pyskindose/badge/?version=latest)](http://pyskindose.readthedocs.io/en/latest/?badge=latest)
```
Although some of the pages are still empty, I found the API documentation at the end to be useful.

**Comment by BwKodex** [comment]
> 
> 
> How about a badge for the documentation as well?
> 
> ```
> [Documentation Status](http://pyskindose.readthedocs.io/en/latest/?badge=latest)
> ```
> 
> Although some of the pages are still empty, I found the API documentation at the end to be useful.

Very good suggestion! I've added it as well.

**Review by MaxHellstrom — APPROVED** [review]

**Pull request merged**
